name: Java CD workflow
on:
- push
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up JDK 14
         uses: actions/setup-java@v1
         with:
            java-version: 14.0.2
      -  name: Test
         run: mvn test
      -  name: Deploy
         env:
            GITHUB_USERNAME: GiuliaPais
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |-
            mkdir ~/.m2
            echo "<servers>
            <server>
            <id>github</id>
            <username>${env.GITHUB_USERNAME}</username>
            <password>${env.GITHUB_TOKEN}</password>
            </server>
            </servers>
            </settings>" > ~/.m2/settings.xml
            mvn deploy