name: Java CI workflow for macos
on:
- push
jobs:
   test:
      runs-on: macos-latest
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up JDK 14
         uses: actions/setup-java@v1
         with:
            java-version: 14.0.2
      -  name: Test
         run: mvn test
